name: Laboratorio de Ingenieria Inversa del Kernel

on:
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  analizar-binario:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar únicamente el archivo kernel
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          kernel_descomprimido
        sparse-checkout-cone-mode: false

    - name: Instalar QEMU, GDB y Herramientas de DTB
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-arm gdb-multiarch device-tree-compiler

    - name: Descargar y Extraer el DTB Real del Infinix
      run: |
        # Descargamos el dtb.img desde el GitHub que me pasaste
        curl -L -o dtb.img https://github.com/thequantumcog/device_infinix_X6831/raw/12.1/prebuilt/dtb.img
        
        # Intentamos extraer el primer DTB limpio del paquete img
        # Los dtb.img de MediaTek suelen empezar con la firma "DTBH" o directamente "0xd00dfeed"
        # Usamos dtc para verificar o separar si es necesario. Por ahora lo trataremos directamente:
        cp dtb.img infinix.dtb

    - name: Iniciar QEMU con el DTB del Infinix
      run: |
        # Agregamos el parámetro -dtb para que el Kernel lea tu hardware real
        qemu-system-aarch64 -M virt -cpu cortex-a57 -kernel ./kernel_descomprimido -dtb ./infinix.dtb -nographic -s -S > qemu_output.log 2>&1 &
        sleep 2 

    - name: Crear script de traducción para GDB
      run: |
        cat << 'EOF' > gdb_commands.txt
        target remote :1234
        set architecture aarch64
        
        # Ponemos el breakpoint justo DESPUÉS de que se encienda la MMU
        break *0x4105c3bc
        
        continue
        
        echo \n--- ¡MMU ACTIVADA CON DTB REAL! ---\n
        x/20i $pc
        
        echo \n--- REGISTROS POST-MMU ---\n
        info registers
        quit
        EOF

    - name: Ejecutar GDB y extraer el volcado de memoria
      run: |
        gdb-multiarch -batch -x gdb_commands.txt > resultado_memoria.txt

    - name: Guardar los resultados como un archivo descargable
      uses: actions/upload-artifact@v4
      with:
        name: reporte-analisis-kernel
        path: |
          resultado_memoria.txt
          qemu_output.log
