name: Laboratorio de Ingenieria Inversa del Kernel

on:
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  analizar-binario:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar únicamente el archivo kernel
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          kernel_descomprimido
        sparse-checkout-cone-mode: false

    - name: Instalar QEMU y GDB Multiarch
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-arm gdb-multiarch

    - name: Iniciar QEMU en segundo plano (Emulación congelada)
      run: |
        qemu-system-aarch64 -M virt -cpu cortex-a57 -kernel ./kernel_descomprimido -nographic -s -S > qemu_output.log 2>&1 &
        sleep 2 

    - name: Crear script de traducción para GDB
      run: |
        cat << 'EOF' > gdb_commands.txt
        target remote :1234
        set architecture aarch64
        
        # CAMBIO CLAVE: Ponemos el breakpoint en el destino real del salto (stext)
        break *0x41580000
        
        continue
        
        echo \n--- ¡LLEGAMOS A LA INICIALIZACIÓN REAL DEL KERNEL (stext)! ---\n
        x/30i $pc
        
        echo \n--- ESTADO DE LOS REGISTROS EN STEXT ---\n
        info registers
        quit
        EOF

    - name: Ejecutar GDB y extraer el volcado de memoria
      run: |
        gdb-multiarch -batch -x gdb_commands.txt > resultado_memoria.txt

    - name: Guardar los resultados como un archivo descargable
      uses: actions/upload-artifact@v4
      with:
        name: reporte-analisis-kernel
        path: |
          resultado_memoria.txt
          qemu_output.log
